spring.application.name=guia-consumidor

server.port=${SERVER_PORT:8081}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.datasource.url=${H2_URL:jdbc:h2:file:/app/data/guiasdb;AUTO_SERVER=TRUE}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${H2_USERNAME:sa}
spring.datasource.password=${H2_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guias}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guias123}
spring.rabbitmq.listener.simple.default-requeue-rejected=false

aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket=${AWS_S3_BUCKET:inscripcionesclouds4}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always