spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_B2C_ISSUER_URI}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_B2C_JWK_SET_URI}

azure.b2c.audience=${AZURE_B2C_AUDIENCE}

azure.b2c.role-claim=${AZURE_ROLE_CLAIM:extension_guiaRole}